### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Jerry-kiwi** [EZUSoft/AnotherDXF2Shape#6]
Windows
QGIS 2.18.4
GDAL 2.2.3
I'm getting error 
""
![screenshot 2017-12-16 17 53 13](https://user-images.githubusercontent.com/8778463/34071651-7b56cbe8-e28a-11e7-8894-a459c8b3eb31.png)

Ubuntu
QGIS 2.18.15
GDAL 2.2 installed (due to gdalinfo --version), but GDAL 1.11.3 is displayed at EZSoft window

Error: QGIS simply closes without any message.

**Comment by EZUSoft** [comment]
Please upload the dxf

**Comment by Jerry-kiwi** [comment]
Due to some reasons i can't share dxf to public:(  But i can send any logs, which are needed (if you say, where to see them)

Also I'm confused with fact, that
**GDAL 2.2 installed (due to gdalinfo --version), but GDAL 1.11.3 is displayed at EZSoft window**

**Comment by EZUSoft** [comment]
DXF is a pretty complex format. Without the specific file I can not help remotely.
You can send me the DXF directly by mail. The address can be found in the QGIS About menu
![unbenannt](https://user-images.githubusercontent.com/19267407/34092808-971c03e8-e3c5-11e7-9fef-f671e6f85a5d.png)

> Also I'm confused with fact, that
GDAL 2.2 installed (due to gdalinfo --version), but GDAL 1.11.3 is displayed at EZSoft window
Test this in the QGIS.python console:
`import gdal
print (gdal.VersionInfo("GDAL_RELEASE_DATE"))`

**Comment by Jerry-kiwi** [comment]
```
In [75]: import gdal
In [76]: print (gdal.VersionInfo("GDAL_RELEASE_DATE"))
GDAL 2.2.2, released 2017/09/15
```

**Comment by EZUSoft** [comment]
Please note that the file is quite large and the presentation is very complex.
It takes a long time for QGIS to render the file after conversion.

Are you using a 32-bit version of QGIS?
The 64-bit version requires 1.9 GB of RAM for this file.
The 32-bit version of QGIS can not display this amount of data since only about 1.7 GB can be addressed.

BTW: After displaying the window
![screenshot 2017-12-16 17 53 13](https://user-images.githubusercontent.com/8778463/34071651-7b56cbe8-e28a-11e7-8894-a459c8b3eb31.png)
The plugin has actually finished its work. After that, QGIS must display the data. If there is a crash, the problem probably lies with QGIS itself.

**Comment by Jerry-kiwi** [comment]
I use 64bit QGIS on 64Bit Ubuntu 16.04 on machine with 8GB RAM

**Comment by Jerry-kiwi** [comment]
I use 64bit QGIS on 64Bit Ubuntu 16.04 on machine with 8GB RAM

**Comment by EZUSoft** [comment]
Nevertheless, I think that the QGIS resources are not sufficient for presentation.
Which options do you use when importing? **You should definitely disable the "group layer" option.**
These are the settings with which it works with 32-bit:
![unbenannt](https://user-images.githubusercontent.com/19267407/34098048-688ab072-e3db-11e7-95f2-b9c4a5403c12.png)


I will test Linux this evening.

**Comment by EZUSoft** [comment]
With me the DXF runs also under Linux without problems.
![bildschirmfoto](https://user-images.githubusercontent.com/19267407/34122846-039e6dc2-e42e-11e7-9bf3-084bf885fb45.png)
Unfortunately, I can not help you now.

**Comment by Jerry-kiwi** [comment]
I've switched to ubutnugis repo and now everything works okay. Error with incomplete field is still remains, but it is not plugin problem. issue canbe closed, Thanks for help.
